# Generated by Django 4.2 on 2023-04-14 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Thread creation date and time')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Thread last update date and time')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Owners of a thread')),
            ],
            options={
                'db_table': 'thread',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096, verbose_name='Message text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Message creation date and time')),
                ('is_read', models.BooleanField(default=False, verbose_name='Message is read by all participants of a thread')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='User that sent this message')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.thread', verbose_name='Thread a message belongs to')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
